using UnityEngine;

// Marks a GameObject as a middle tile generated by MovingPlatformLength, so rebuilds can
// find and clear exactly the tiles they created without relying on a cached reference list.
public class MovingPlatformMiddleTile : MonoBehaviour
{
}
